export interface ClimateTopic {
  id: string;
  theme: string;
}

export const CLIMATE_TOPICS: ClimateTopic[] = [
  { id: 'fossil-fuel-giants', theme: 'Fossil fuel corporations and their role in global emissions' },
  { id: 'billionaire-carbon', theme: 'Billionaire lifestyles and their outsized carbon footprints' },
  { id: 'big-meat-industry', theme: 'The meat and dairy industry\'s climate impact' },
  { id: 'big-tech-energy', theme: 'Big tech companies and their massive energy consumption' },
  { id: 'plastic-producers', theme: 'Corporations behind the global plastic crisis' },
  { id: 'greenwashing-exposed', theme: 'Corporate greenwashing and false climate promises' },
  { id: 'banking-fossil-fuels', theme: 'Banks and financial institutions funding fossil fuels' },
  { id: 'lobbying-machine', theme: 'Fossil fuel lobbying and climate denial funding' },
  { id: 'ceo-vs-workers', theme: 'Executive profits at polluting companies vs community impact' },
  { id: 'food-giants-deforestation', theme: 'Corporate-driven deforestation of tropical forests' },
  { id: 'auto-industry-delay', theme: 'How the auto industry delayed clean transportation' },
  { id: 'shipping-aviation-hidden', theme: 'Hidden emissions from shipping, aviation, and cruise industries' },
  { id: 'pharma-chemical-pollution', theme: 'Chemical industry contamination of water, soil, and health' },
  { id: 'mining-destruction', theme: 'Environmental and human cost of the mining industry' },
  { id: 'climate-refugees', theme: 'Climate refugees and forced displacement' },
  { id: 'economic-losses', theme: 'The staggering economic cost of climate change' },
  { id: 'biodiversity-collapse', theme: 'Mass extinction and biodiversity collapse driven by corporations' },
  { id: 'extreme-weather-cost', theme: 'Extreme weather events and their growing human toll' },
  { id: 'food-security-crisis', theme: 'Climate change threatening global food security' },
  { id: 'health-crisis', theme: 'Climate change as a public health emergency' },
  { id: 'arctic-ice-melt', theme: 'Arctic and Antarctic ice melt and sea level rise' },
  { id: 'ocean-acidification', theme: 'Ocean acidification and marine ecosystem collapse' },
  { id: 'insurance-retreat', theme: 'The insurance industry retreating from climate risk' },
  { id: 'climate-inequality', theme: 'Climate inequality — who pollutes vs who suffers' },
  { id: 'fossil-fuel-subsidies', theme: 'Governments subsidizing fossil fuels with taxpayer money' },
  { id: 'child-labor-supply-chains', theme: 'Child labor in climate-linked supply chains' },
  { id: 'tipping-points', theme: 'Climate tipping points we may have already crossed' },
  { id: 'environmental-racism', theme: 'Environmental racism and pollution in marginalized communities' },
  { id: 'climate-migration-internal', theme: 'Climate migration and displacement within countries' },
  { id: 'climate-anxiety', theme: 'Mental health and climate anxiety' },
  { id: 'indigenous-land-defenders', theme: 'Indigenous land defenders killed for protecting forests' },
  { id: 'women-and-climate', theme: 'Women bearing the brunt of climate change' },
  { id: 'soil-degradation', theme: 'Soil degradation and the collapse of farmland' },
  { id: 'coral-reef-death', theme: 'Coral reef death and what we lose at each degree of warming' },
  { id: 'microplastics-in-humans', theme: 'Microplastics found inside the human body' },
  { id: 'ocean-dead-zones', theme: 'Ocean dead zones spreading across the world' },
  { id: 'light-noise-pollution', theme: 'Light and noise pollution disrupting ecosystems' },
  { id: 'wildfires-dead-forests', theme: 'Megafires and dying forests in a warming world' },
  { id: 'climate-lawsuits', theme: 'Climate lawsuits holding corporations and governments accountable' },
  { id: 'renewables-cheaper', theme: 'Renewable energy is already cheaper — so who is blocking it' },
  { id: 'carbon-capture-scam', theme: 'The carbon capture scam propping up fossil fuels' },
  { id: 'ewaste-right-to-repair', theme: 'E-waste mountains and the fight for right to repair' },
];
